server:
  port: 8081
spring:
  application:
    name: hystrix-client
eureka:
  client:
    # 单节点注册中心不需要注册到euraka,也不需要从注册中心获取注册表
    # 是否注册到注册中心
    registerWithEureka: true
    # 是否从注册中心获取注册表
    fetchRegistry: true
    # 服务注册中心路由，对于单节点也不需要配置
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/