spring:
  application:
    name: spring-boot-grap-redpackage
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/red_package?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.yoke.model
  mapperLocations: classpath:mappers/*.xml