server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  instance:
    hostname: localhost
  client:
    # 单节点注册中心不需要注册到euraka,也不需要从注册中心获取注册表
    # 是否注册到注册中心
    registerWithEureka: false
    # 是否从注册中心获取注册表
    fetchRegistry: false
    # 服务注册中心路由，对于单节点也不需要配置
    #serviceUrl:
    #  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/